import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: ['500', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
